<?php

namespace Metafrastis\SystranTranslate;

class SystranTranslate {

	public $sessid;
	public $cfbm;
	public $cookie;
	public $csrf;
	public $queue = [];
	public $response;
	public $responses = [];

	public function translate($args = [], $opts = []) {
		if (is_object($args)) {
			$args = json_decode(json_encode($args), true);
		}
		if (is_string($args)) {
			if (($arr = json_decode($args, true))) {
				$args = $arr;
			} else {
				parse_str($args, $arr);
				if ($arr) {
					$args = $arr;
				}
			}
		}
		$args = is_array($args) ? $args : [];
		$args['from'] = isset($args['from']) ? $args['from'] : null;
		$args['to'] = isset($args['to']) ? $args['to'] : null;
		$args['text'] = isset($args['text']) ? $args['text'] : null;
		$args['sessid'] = !empty($args['sessid']) ? $args['sessid'] : $this->sessid;
		if ($args['sessid']) {
			$this->sessid = $args['sessid'];
		}
		$args['cfbm'] = !empty($args['cfbm']) ? $args['cfbm'] : $this->cfbm;
		if ($args['cfbm']) {
			$this->cfbm = $args['cfbm'];
		}
		$args['cookie'] = !empty($args['cookie']) ? $args['cookie'] : $this->cookie;
		if (!$args['cookie']) {
			$args['cookie'] = stream_get_meta_data(tmpfile())['uri'];
		}
		if (!is_file($args['cookie'])) {
			if (is_dir(dirname($args['cookie'])) || mkdir(dirname($args['cookie']), 0755, true)) {
				touch($args['cookie']);
			}
		}
		if ($args['sessid'] && $args['cfbm'] && is_file($args['cookie']) && !filesize($args['cookie'])) {
			file_put_contents($args['cookie'], '# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_translate.systran.net	FALSE	/	TRUE	'.strval(time()+1200).'	lang	en
#HttpOnly_translate.systran.net	FALSE	/	TRUE	'.strval(time()+1200).'	ses.is-connected	0
#HttpOnly_translate.systran.net	FALSE	/	TRUE	'.strval(time()+1200).'	ses.sid	'.$args['sessid'].'
#HttpOnly_.systran.net	TRUE	/	TRUE	'.strval(time()+1200).'	__cf_bm	'.$args['cfbm']."\x0a");
		}
		if ($args['cookie']) {
			$this->cookie = $args['cookie'];
		}
		$args['csrf'] = !empty($args['csrf']) ? $args['csrf'] : $this->csrf;
		if (!$args['sessid'] || !$args['cfbm'] || !$args['csrf']) {
			$this->home($args, $opts);
			$args['sessid'] = $this->sessid ? $this->sessid : $args['sessid'];
			$args['cfbm'] = $this->cfbm ? $this->cfbm : $args['cfbm'];
			$args['csrf'] = $this->csrf ? $this->csrf : $args['csrf'];
		}
		if ($args['sessid']) {
			$this->sessid = $args['sessid'];
		}
		if ($args['cfbm']) {
			$this->cfbm = $args['cfbm'];
		}
		if ($args['csrf']) {
			$this->csrf = $args['csrf'];
		}
		$args['signature'] = !empty($args['signature']) ? $args['signature'] : hash('sha256', $args['csrf'].'.'.$args['from'].'.'.$args['to'].'.'.implode(',', explode("\x0a", $args['text'])));
		if (!$args['from']) {
			return false;
		}
		if (!$args['to']) {
			return false;
		}
		if (!$args['text']) {
			return false;
		}
		$url = 'https://translate.systran.net/translate/json';
		$headers = [
			'Accept: '.'*'.'/'.'*',
			'Accept-Language: en-US,en;q=0.5',
			'Connection: keep-alive',
			'Content-Type: application/json',
			'Origin: https://translate.systran.net',
			'Referer: https://translate.systran.net/',
			'Sec-Fetch-Dest: empty',
			'Sec-Fetch-Mode: cors',
			'Sec-Fetch-Site: same-origin',
			'TE: trailers',
			'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0',
			'X-CSRF-Token: '.$args['csrf'],
			'X-Requested-With: XMLHttpRequest',
			'x-translation-signature: '.$args['signature'],
			'x-user-agent: Translation Box',
		];
		$params = ['profileId' => null, 'owner' => null, 'domain' => null, 'size' => null, 'input' => explode("\x0a", $args['text']), 'source' => $args['from'], 'target' => $args['to']];
		$params = json_encode($params);
		$options = [
			CURLOPT_CERTINFO => true,
			CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_2_0,
			CURLOPT_SSL_VERIFYHOST => 2,
			CURLOPT_SSL_VERIFYPEER => 2,
			CURLOPT_COOKIEFILE => $args['cookie'],
			CURLOPT_COOKIEJAR => $args['cookie'],
		];
		$options = array_replace($options, $opts);
		$queue = isset($args['queue']) ? 'translate' : false;
		$response = $this->post($url, $headers, $params, $options, $queue);
		if (!$queue) {
			$this->response = $response;
		}
		if ($queue) {
			return;
		}
		$json = json_decode($response['body'], true);
		if (!isset($json['outputs'][0])) {
			return false;
		}
		$translation = '';
		foreach ($json['outputs'] as $output_index => $output_data) {
			if (isset($json['outputs'][$output_index]['output']['documents'][0]['trans_units'][0]['sentences'][0]['alt_transes'][0]['target']['text'])) {
				$translation .= $json['outputs'][$output_index]['output']['documents'][0]['trans_units'][0]['sentences'][0]['alt_transes'][0]['target']['text'];
			}
			$translation .= "\x0a";
		}
		$translation = trim($translation);
		if ($translation === '') {
			return false;
		}
		return $translation;
	}

	public function home($args = [], $opts = []) {
		$args['cookie'] = isset($args['cookie']) ? $args['cookie'] : $this->cookie;
		if (!$args['cookie']) {
			$this->cookie = $args['cookie'] = stream_get_meta_data(tmpfile())['uri'];
		}
		if ($args['cookie']) {
			$this->cookie = $args['cookie'];
		}
		$args['force'] = isset($args['force']) ? $args['force'] : false;
		if ($this->sessid && $this->cfbm && $this->csrf && !$args['force']) {
			return ['sessid' => $this->sessid, 'cfbm' => $this->cfbm, 'csrf' => $this->csrf];
		}
		$url = 'https://translate.systran.net/';
		$headers = [
			'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,'.'*'.'/'.'*'.';q=0.8',
			'Accept-Language: en-US,en;q=0.5',
			'Connection: keep-alive',
			'Sec-Fetch-Dest: document',
			'Sec-Fetch-Mode: navigate',
			'Sec-Fetch-Site: none',
			'Sec-Fetch-User: ?1',
			'Upgrade-Insecure-Requests: 1',
			'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0',
		];
		$params = null;
		$options = [
			CURLOPT_CERTINFO => true,
			CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			CURLOPT_SSL_VERIFYHOST => 2,
			CURLOPT_SSL_VERIFYPEER => 2,
			CURLOPT_COOKIEFILE => $args['cookie'],
			CURLOPT_COOKIEJAR => $args['cookie'],
		];
		$options = array_replace($options, $opts);
		$queue = false;
		for ($j = 0; $j < 2; $j++) {
			$response = $this->get($url, $headers, $params, $options);
			$this->response = $response;
			if (preg_match('`Set\-Cookie[\x00-\x20\x7f]*\:[\x00-\x20\x7f]*ses\.sid\=([^\;\x0d\x0a]+)`i', $response['head'], $match)) {
				$this->sessid = $match[1];
			}
			if (preg_match('`Set\-Cookie[\x00-\x20\x7f]*\:[\x00-\x20\x7f]*__cf_bm\=([^\;\x0d\x0a]+)`i', $response['head'], $match)) {
				$this->cfbm = $match[1];
			}
			if (preg_match('`window\.csrfToken[\x00-\x20\x7f]*\=[\x00-\x20\x7f]*[\x27]([^\x27]+)[\x27]`', $response['body'], $match)) {
				$this->csrf = $match[1];
				break;
			} elseif (preg_match('`window\.csrfToken[\x00-\x20\x7f]*\=[\x00-\x20\x7f]*[\x22]([^\x22]+)[\x22]`', $response['body'], $match)) {
				$this->csrf = $match[1];
				break;
			} elseif (preg_match('`[\x22\x27]?X\-CSRF\-Token[\x22\x27]?[\x00-\x20\x7f]*\:[\x00-\x20\x7f]*[\x27]([^\x27]+)[\x27]`', $response['body'], $match)) {
				$this->csrf = $match[1];
				break;
			} elseif (preg_match('`[\x22\x27]?X\-CSRF\-Token[\x22\x27]?[\x00-\x20\x7f]*\:[\x00-\x20\x7f]*[\x22]([^\x22]+)[\x22]`', $response['body'], $match)) {
				$this->csrf = $match[1];
				break;
			}
		}
		return ['sessid' => $this->sessid, 'cfbm' => $this->cfbm, 'csrf' => $this->csrf];
	}

	public function request($method, $url, $headers = [], $params = null, $options = [], $queue = false) {
		if (is_string($headers)) {
			$headers = array_values(array_filter(array_map('trim', explode("\x0a", $headers))));
		}
		if (is_array($headers) && isset($headers['headers']) && is_array($headers['headers'])) {
			$headers = $headers['headers'];
		}
		if (is_array($headers)) {
			foreach ($headers as $key => $value) {
				if (is_string($key) && !is_numeric($key)) {
					$headers[$key] = sprintf('%s: %s', $key, $value);
				}
			}
		}
		$opts = [];
		$opts[CURLINFO_HEADER_OUT] = true;
		$opts[CURLOPT_CONNECTTIMEOUT] = 5;
		$opts[CURLOPT_CUSTOMREQUEST] = strtoupper($method);
		$opts[CURLOPT_ENCODING] = '';
		$opts[CURLOPT_FOLLOWLOCATION] = false;
		$opts[CURLOPT_HEADER] = true;
		$opts[CURLOPT_HTTPHEADER] = $headers;
		if ($params !== null) {
			$opts[CURLOPT_POSTFIELDS] = is_array($params) || is_object($params) ? http_build_query($params) : $params;
		}
		$opts[CURLOPT_RETURNTRANSFER] = true;
		$opts[CURLOPT_SSL_VERIFYHOST] = false;
		$opts[CURLOPT_SSL_VERIFYPEER] = false;
		$opts[CURLOPT_TIMEOUT] = 10;
		$opts[CURLOPT_URL] = $url;
		foreach ($opts as $key => $value) {
			if (!array_key_exists($key, $options)) {
				$options[$key] = $value;
			}
		}
		if ($queue) {
			$this->queue[] = ['options' => $options, 'queue' => $queue];
			return;
		}
		$follow = false;
		if ($options[CURLOPT_FOLLOWLOCATION]) {
			$follow = true;
			$options[CURLOPT_FOLLOWLOCATION] = false;
		}
		$errors = 2;
		$redirects = isset($options[CURLOPT_MAXREDIRS]) ? $options[CURLOPT_MAXREDIRS] : 5;
		while (true) {
			$ch = curl_init();
			curl_setopt_array($ch, $options);
			$body = curl_exec($ch);
			$info = curl_getinfo($ch);
			$head = substr($body, 0, $info['header_size']);
			$body = substr($body, $info['header_size']);
			$error = curl_error($ch);
			$errno = curl_errno($ch);
			curl_close($ch);
			$response = [
				'info' => $info,
				'head' => $head,
				'body' => $body,
				'error' => $error,
				'errno' => $errno,
			];
			if ($error || $errno) {
				if ($errors > 0) {
					$errors--;
					continue;
				}
			} elseif ($info['redirect_url'] && $follow) {
				if ($redirects > 0) {
					$redirects--;
					$options[CURLOPT_URL] = $info['redirect_url'];
					continue;
				}
			}
			break;
		}
		return $response;
	}

	public function get($url, $headers = [], $params = null, $options = [], $queue = false) {
		return $this->request('GET', $url, $headers, $params, $options, $queue);
	}

	public function post($url, $headers = [], $params = [], $options = [], $queue = false) {
		return $this->request('POST', $url, $headers, $params, $options, $queue);
	}

	public function multi($args = []) {
		if (!$this->queue) {
			return [];
		}
		$mh = curl_multi_init();
		$chs = [];
		foreach ($this->queue as $key => $request) {
			$ch = curl_init();
			$chs[$key] = $ch;
			curl_setopt_array($ch, $request['options']);
			curl_multi_add_handle($mh, $ch);
		}
		$running = 1;
		do {
			curl_multi_exec($mh, $running);
		} while ($running);
		$responses = [];
		foreach ($chs as $key => $ch) {
			curl_multi_remove_handle($mh, $ch);
			$body = curl_multi_getcontent($ch);
			$info = curl_getinfo($ch);
			$head = substr($body, 0, $info['header_size']);
			$body = substr($body, $info['header_size']);
			$error = curl_error($ch);
			$errno = curl_errno($ch);
			curl_close($ch);
			$response = [
				'info' => $info,
				'head' => $head,
				'body' => $body,
				'error' => $error,
				'errno' => $errno,
			];
			$this->responses[$key] = $response;
			$options = $this->queue[$key]['options'];
			if ($this->queue[$key]['queue'] === 'translate' || strpos($options[CURLOPT_URL], '/translate/json') !== false) {
				$json = json_decode($body, true);
				if (!isset($json['outputs'][0])) {
					$responses[$key] = false;
					continue;
				}
				$translation = '';
				foreach ($json['outputs'] as $output_index => $output_data) {
					if (isset($json['outputs'][$output_index]['output']['documents'][0]['trans_units'][0]['sentences'][0]['alt_transes'][0]['target']['text'])) {
						$translation .= $json['outputs'][$output_index]['output']['documents'][0]['trans_units'][0]['sentences'][0]['alt_transes'][0]['target']['text'];
					}
					$translation .= "\x0a";
				}
				$translation = trim($translation);
				if ($translation === '') {
					$responses[$key] = false;
					continue;
				}
				$responses[$key] = $translation;
			} else {
				$responses[$key] = $body;
			}
		}
		curl_multi_close($mh);
		$this->queue = [];
		return $responses;
	}

}
